---
- name: Preparing sshd_config for direct root key-pair authorization.
  hosts: proxmox_hosts
  tasks:
  - name: Set authorized keys taken from url
    authorized_key:
      user: root
      state: present
      key: https://your.url/to/your/public/key
